# Generated by Django 4.2.27 on 2026-01-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school_level', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('o-level', 'O-Level'), ('a-level', 'A-Level')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Previous School',
                'verbose_name_plural': 'Previous Schools',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='student_profile_pic')),
                ('physical_disabilities_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('examination_number', models.CharField(blank=True, max_length=30, null=True)),
                ('previously_examination_number', models.CharField(blank=True, max_length=30, null=True)),
                ('serial_number', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('admission_year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classlevel')),
                ('optional_subjects', models.ManyToManyField(blank=True, related_name='optional_students', to='core.subject')),
                ('previous_class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_students', to='core.classlevel')),
                ('previous_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.previousschool')),
                ('stream_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.streamclass')),
                ('transfer_from_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_students', to='students.previousschool')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Cousin', 'Cousin'), ('Stepfather', 'Stepfather'), ('Stepmother', 'Stepmother'), ('Other', 'Other')], default='Other', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_phone_number', models.CharField(max_length=20)),
                ('second_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_fee_responsible', models.BooleanField(default=False, help_text='Primary fee payer for this student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(related_name='parents', to='students.student')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('first_name', 'middle_name', 'last_name'), name='unique_student'),
        ),
    ]
