# Generated by Django 4.2.27 on 2026-01-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.academicyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(blank=True, help_text='Generated from Academic Year', null=True),
        ),
    ]
