# Generated by Django 4.2.27 on 2026-01-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_staffs_position_title'),
        ('core', '0001_initial'),
        ('students', '0002_student_academic_year_alter_student_admission_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('CLASS', 'Class Wise'), ('SUBJECT', 'Subject Wise')], max_length=10)),
                ('date', models.DateField()),
                ('period', models.PositiveIntegerField(blank=True, null=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classlevel')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.streamclass')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], max_length=1)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('attendance_session', 'student')},
            },
        ),
    ]
