# Generated by Django 4.2.27 on 2026-01-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_attendancesession_studentattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='teacher',
        ),
    ]
