# Generated by Django 4.2.27 on 2026-02-18 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_bed_hostel_hostelinstallmentplan_hostelroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelpayment',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='students.studenthostelallocation'),
        ),
        migrations.AlterField(
            model_name='hostelpayment',
            name='installment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.hostelinstallmentplan'),
        ),
        migrations.AlterUniqueTogether(
            name='hostelpayment',
            unique_together={('allocation', 'installment_plan')},
        ),
        migrations.CreateModel(
            name='HostelPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('installment', 'Installment'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='students.studenthostelallocation')),
                ('installment_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='students.hostelpayment')),
            ],
        ),
        migrations.RemoveField(
            model_name='hostelpayment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='hostelpayment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='hostelpayment',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='hostelpayment',
            name='status',
        ),
    ]
