# Generated by Django 4.2.27 on 2026-02-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_hostelpayment_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelpaymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money'), ('cheque', 'Cheque')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelpaymenttransaction',
            name='transaction_number',
            field=models.CharField(blank=True, help_text='Bank reference, mobile transaction ID, or cheque number', max_length=100, null=True),
        ),
    ]
