# Generated by Django 4.2.27 on 2026-02-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('educational_level', models.ForeignKey(limit_choices_to={'code': 'A_LEVEL'}, on_delete=django.db.models.deletion.CASCADE, to='core.educationallevel')),
            ],
        ),
        migrations.CreateModel(
            name='CombinationSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CORE', 'Core Subject'), ('SUB', 'Subsidiary Subject')], max_length=5)),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.combination')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('combination', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='combination',
            name='subjects',
            field=models.ManyToManyField(through='core.CombinationSubject', to='core.subject'),
        ),
    ]
