# Generated by Django 4.2.27 on 2026-01-18 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0002_alter_staffs_role_systemlog_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffs',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='role',
        ),
        migrations.AddField(
            model_name='staffs',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('part_time', 'Part Time'), ('temporary', 'Temporary')], default='permanent', max_length=50),
        ),
        migrations.AddField(
            model_name='staffs',
            name='position_title',
            field=models.CharField(blank=True, help_text='Official position/title (e.g., Senior Teacher, Head of Department)', max_length=100),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for department', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_heading', to='accounts.staffs')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='staffs',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Primary department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='accounts.department'),
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('class', 'Class Level'), ('stream', 'Stream Specific'), ('both', 'Class and Stream')], default='class', max_length=20)),
                ('is_class_teacher', models.BooleanField(default=False, help_text='Is this staff the class teacher for this class/stream?')),
                ('period_count', models.PositiveIntegerField(default=0, help_text='Number of periods per week')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='core.academicyear')),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='core.classlevel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='accounts.staffs')),
                ('stream_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='core.streamclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='core.subject')),
            ],
            options={
                'verbose_name': 'Teaching Assignment',
                'verbose_name_plural': 'Teaching Assignments',
                'unique_together': {('staff', 'subject', 'class_level', 'academic_year'), ('staff', 'subject', 'stream_class', 'academic_year')},
            },
        ),
    ]
