# Generated by Django 4.2.27 on 2026-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staffs_options_remove_staffs_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='position_title',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Secretary', 'Secretary'), ('Headmaster', 'Headmaster'), ('Accountant', 'Accountant'), ('Librarian', 'Librarian'), ('Administrator', 'Administrator'), ('Staff', 'Staff')], help_text='Official position/title (e.g., Senior Teacher, Head of Department)', max_length=100),
        ),
    ]
